{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-crypto",
    "version": "6.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.2.1.jar",
          "url": "spring-security-crypto-6.2.1.jar",
          "size": 84189,
          "sha512": "b6a009c587ae6aeccedaaebd3da5f55f4a211fdd5e16fa24c34163faa9ddd20c13ffb6b2ebf06969f19e75260e4e666019e446373cb206847b63af223fb481b0",
          "sha256": "34e7e56af73caa4b1d71bc57a6006777fa1c5b590cea405bd962172cd42c47d4",
          "sha1": "d7c4f4e8fe5ae84dd1da76094ee8a0a7e214923d",
          "md5": "3b76db12e0661ea929c45559e3612203"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.2.1.jar",
          "url": "spring-security-crypto-6.2.1.jar",
          "size": 84189,
          "sha512": "b6a009c587ae6aeccedaaebd3da5f55f4a211fdd5e16fa24c34163faa9ddd20c13ffb6b2ebf06969f19e75260e4e666019e446373cb206847b63af223fb481b0",
          "sha256": "34e7e56af73caa4b1d71bc57a6006777fa1c5b590cea405bd962172cd42c47d4",
          "sha1": "d7c4f4e8fe5ae84dd1da76094ee8a0a7e214923d",
          "md5": "3b76db12e0661ea929c45559e3612203"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.2.1-javadoc.jar",
          "url": "spring-security-crypto-6.2.1-javadoc.jar",
          "size": 225064,
          "sha512": "4e49bcd2732958a891e0dbd1dea5c8babbeba16047182660591f7c697adac02576a7fa246a07d864a721044b4768d4f1237e07de222e214a17c2c0444bd0c4d7",
          "sha256": "7f0f68f4d4f704b89b57075690227cd9b513dab16f9226e40cf6c6ae57bb0d4c",
          "sha1": "6b30f3e3c9ede6a76f0c89a9ed830467ca6d7631",
          "md5": "464322c05f12911c367b768fe824934a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.2.1-sources.jar",
          "url": "spring-security-crypto-6.2.1-sources.jar",
          "size": 76810,
          "sha512": "7384d9b0daaa8bcb3ff08bf978e09392ebd4470fe96521aef35cb81ecad635cda0ed1072a68e0a48f21803a9400fa3841fa327ed6b797bdb9ab3a848a17225f0",
          "sha256": "0c697c8e0109b5ea5c185884fb8e7e621258fc3960409e9f73e3067e684efe42",
          "sha1": "3f77f4348ae91ecdc10180d623df963e1e003182",
          "md5": "7e2afc94918c910ff28749b8593b0020"
        }
      ]
    }
  ]
}
