{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.okhttp3",
    "module": "logging-interceptor",
    "version": "5.0.0-alpha.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-interceptor-5.0.0-alpha.12.jar",
          "url": "logging-interceptor-5.0.0-alpha.12.jar",
          "size": 16947,
          "sha512": "daaf138efd78dcaf8e10a146e5f41a299e60ac50cfb0e7ea4b3c912eba89c60459c94d479cd86b109da1e6253f0c65a894a33326195b349692d93272b828ea22",
          "sha256": "ce5fd6d8f4f6dd2804fd1a38c7550368222fa124316ccf1fa53cb2ebe819b8ec",
          "sha1": "39e57bab216d200b965ff60723486d06d89dd6e4",
          "md5": "9531fc599e0da10cc40a22ab0ec782ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-interceptor-5.0.0-alpha.12.jar",
          "url": "logging-interceptor-5.0.0-alpha.12.jar",
          "size": 16947,
          "sha512": "daaf138efd78dcaf8e10a146e5f41a299e60ac50cfb0e7ea4b3c912eba89c60459c94d479cd86b109da1e6253f0c65a894a33326195b349692d93272b828ea22",
          "sha256": "ce5fd6d8f4f6dd2804fd1a38c7550368222fa124316ccf1fa53cb2ebe819b8ec",
          "sha1": "39e57bab216d200b965ff60723486d06d89dd6e4",
          "md5": "9531fc599e0da10cc40a22ab0ec782ec"
        }
      ]
    }
  ]
}
