{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-security",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.2.jar",
          "url": "spring-boot-starter-security-3.2.2.jar",
          "size": 4741,
          "sha512": "95bcf43d590891f68914e3942c2c5b6586d95088ad597a43c62e9182c0518946e570e2d2ed7f7d3c8e8f14b3d000b25e94c620e4559476981ee1b298c608aab4",
          "sha256": "843270547aa6aa87208237b6e2f0530eeb4c1332f9592bfb648c27f267ca1917",
          "sha1": "79676d6fe68878890e26be10ecab126f472d7c0f",
          "md5": "f2a931f6117cca9a20d2f69cb63c410d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.2.jar",
          "url": "spring-boot-starter-security-3.2.2.jar",
          "size": 4741,
          "sha512": "95bcf43d590891f68914e3942c2c5b6586d95088ad597a43c62e9182c0518946e570e2d2ed7f7d3c8e8f14b3d000b25e94c620e4559476981ee1b298c608aab4",
          "sha256": "843270547aa6aa87208237b6e2f0530eeb4c1332f9592bfb648c27f267ca1917",
          "sha1": "79676d6fe68878890e26be10ecab126f472d7c0f",
          "md5": "f2a931f6117cca9a20d2f69cb63c410d"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.2.jar",
          "url": "spring-boot-starter-security-3.2.2.jar",
          "size": 4741,
          "sha512": "95bcf43d590891f68914e3942c2c5b6586d95088ad597a43c62e9182c0518946e570e2d2ed7f7d3c8e8f14b3d000b25e94c620e4559476981ee1b298c608aab4",
          "sha256": "843270547aa6aa87208237b6e2f0530eeb4c1332f9592bfb648c27f267ca1917",
          "sha1": "79676d6fe68878890e26be10ecab126f472d7c0f",
          "md5": "f2a931f6117cca9a20d2f69cb63c410d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-security-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.2.jar",
          "url": "spring-boot-starter-security-3.2.2.jar",
          "size": 4741,
          "sha512": "95bcf43d590891f68914e3942c2c5b6586d95088ad597a43c62e9182c0518946e570e2d2ed7f7d3c8e8f14b3d000b25e94c620e4559476981ee1b298c608aab4",
          "sha256": "843270547aa6aa87208237b6e2f0530eeb4c1332f9592bfb648c27f267ca1917",
          "sha1": "79676d6fe68878890e26be10ecab126f472d7c0f",
          "md5": "f2a931f6117cca9a20d2f69cb63c410d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-security-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.2-javadoc.jar",
          "url": "spring-boot-starter-security-3.2.2-javadoc.jar",
          "size": 4744,
          "sha512": "9301fc31c7bb434fb40389e7bed3eba23a6b1f293b581caf1bf1d27784e456352e79ce5857ce364780e449c79c174d826003ca3c8770723e0a4898f452cf0244",
          "sha256": "c1d741bd43c4f29eddc0074aa4a55881195283e07bd2ad336936b6846628f710",
          "sha1": "504ef6b57fb2de6b036c93955e30bcf3101f69cc",
          "md5": "f73d9d937583a0043e86c86117460db1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.2-sources.jar",
          "url": "spring-boot-starter-security-3.2.2-sources.jar",
          "size": 4743,
          "sha512": "c4b1e33f645d0c99295927493bbcace2affd41d685e72fe938e7cfb60dcd25248cd3dfe9fcf07843de1d6258d3326a79e4ff92a944d1e85481389e694746dedb",
          "sha256": "79b92dde85ba53c878e19c2b3b950dd4a37f619168fa430361f04e16da694a57",
          "sha1": "fe2e8399390b80df620c7110854ca5b7781eee4e",
          "md5": "fe903e7badcebdfb990ef5bbd3aedd67"
        }
      ]
    }
  ]
}
