{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-jpa",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.4.1.Final"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "6.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.2.2.jar",
          "url": "spring-boot-starter-data-jpa-3.2.2.jar",
          "size": 4761,
          "sha512": "b96591f723b5ccb7758d1f8ece3d76253f0371ff025a0016c78268da9c690f1469b0f58af82c77a4a659ba1ec3683802e281178247dc4c46803fef069dc3a1b7",
          "sha256": "c0e4364a84fcc21b727d35d44de5b4b775a2c11d9b97f3701548447e93a6efba",
          "sha1": "65cf3aad09f0218b7dfab849c9b0350d0a9e0d81",
          "md5": "fcc72358d372a2da886379bdbfae90c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.4.1.Final"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "6.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.2.2.jar",
          "url": "spring-boot-starter-data-jpa-3.2.2.jar",
          "size": 4761,
          "sha512": "b96591f723b5ccb7758d1f8ece3d76253f0371ff025a0016c78268da9c690f1469b0f58af82c77a4a659ba1ec3683802e281178247dc4c46803fef069dc3a1b7",
          "sha256": "c0e4364a84fcc21b727d35d44de5b4b775a2c11d9b97f3701548447e93a6efba",
          "sha1": "65cf3aad09f0218b7dfab849c9b0350d0a9e0d81",
          "md5": "fcc72358d372a2da886379bdbfae90c4"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.2.2.jar",
          "url": "spring-boot-starter-data-jpa-3.2.2.jar",
          "size": 4761,
          "sha512": "b96591f723b5ccb7758d1f8ece3d76253f0371ff025a0016c78268da9c690f1469b0f58af82c77a4a659ba1ec3683802e281178247dc4c46803fef069dc3a1b7",
          "sha256": "c0e4364a84fcc21b727d35d44de5b4b775a2c11d9b97f3701548447e93a6efba",
          "sha1": "65cf3aad09f0218b7dfab849c9b0350d0a9e0d81",
          "md5": "fcc72358d372a2da886379bdbfae90c4"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.2.2.jar",
          "url": "spring-boot-starter-data-jpa-3.2.2.jar",
          "size": 4761,
          "sha512": "b96591f723b5ccb7758d1f8ece3d76253f0371ff025a0016c78268da9c690f1469b0f58af82c77a4a659ba1ec3683802e281178247dc4c46803fef069dc3a1b7",
          "sha256": "c0e4364a84fcc21b727d35d44de5b4b775a2c11d9b97f3701548447e93a6efba",
          "sha1": "65cf3aad09f0218b7dfab849c9b0350d0a9e0d81",
          "md5": "fcc72358d372a2da886379bdbfae90c4"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.2.2-javadoc.jar",
          "url": "spring-boot-starter-data-jpa-3.2.2-javadoc.jar",
          "size": 4747,
          "sha512": "50ec75e6adddd66a4d5999d2cabbe68a8846bdd24210e1b38f97a47cdbdf260cedeb5a9960ec0e22863f54d3e1d8f4214e95882c184ba12693762d36e3d3229d",
          "sha256": "38dc21212d7a91749b23a633111d0634bda4af3d6a69e9db9ea4de9959c2715b",
          "sha1": "b1b7c59db4baee8ce81c45a497058414e59f3b38",
          "md5": "b3f285c67983e96b579fe762b5ef47a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-3.2.2-sources.jar",
          "url": "spring-boot-starter-data-jpa-3.2.2-sources.jar",
          "size": 4746,
          "sha512": "88527fb6b1133b43153d63e9d29147e77949c46571db921effca4ad59db97c57276d3a276db85b0da4c3ecf7b3a41f1e2c7912aa6764ba88a9725c1d160aa01b",
          "sha256": "b2102fb5b64b1db6df4da088af9e212fc2d18f79dff80be62ca2781df602821f",
          "sha1": "b10c239bcc38e88eba88ce1d0fb7cee26d88dd0c",
          "md5": "c4984e4d2f4fe1f3180224a73358f29e"
        }
      ]
    }
  ]
}
