{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-tx",
    "version": "6.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-tx-6.1.3.jar",
          "url": "spring-tx-6.1.3.jar",
          "size": 284337,
          "sha512": "86cd8f9f69de58ee57847b9ebe6461faae8ec01fd2e4ef47cce416fbb74fb8fb24c17642a8191253a73d9a3f62dfc35b276b116a7a0510d61ba6b7f061dadc08",
          "sha256": "a67bb4a9bff7b38dae4055a85cb1a3a21309f5eb15a38113a6a4f9b600fd6f51",
          "sha1": "7750337bf46a2ff248685915c7cc88d3bef2f666",
          "md5": "f4fc2a933dfab72a22d96c8cecdb0969"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-tx-6.1.3.jar",
          "url": "spring-tx-6.1.3.jar",
          "size": 284337,
          "sha512": "86cd8f9f69de58ee57847b9ebe6461faae8ec01fd2e4ef47cce416fbb74fb8fb24c17642a8191253a73d9a3f62dfc35b276b116a7a0510d61ba6b7f061dadc08",
          "sha256": "a67bb4a9bff7b38dae4055a85cb1a3a21309f5eb15a38113a6a4f9b600fd6f51",
          "sha1": "7750337bf46a2ff248685915c7cc88d3bef2f666",
          "md5": "f4fc2a933dfab72a22d96c8cecdb0969"
        }
      ]
    }
  ]
}
