{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-validation",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.18"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.1.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-3.2.2.jar",
          "url": "spring-boot-starter-validation-3.2.2.jar",
          "size": 4767,
          "sha512": "7700824d66abba3642d76f377d5a5b199dd27802ffb2c88ae896019e6238551585690aa1eba8f2d6eb3fa00dccc419c0a052abb05948163eed3dc5f06e77019a",
          "sha256": "4ad5b72664bd6ae25ce000ef4f394fa59af33bc9a87eadd538596adae1ae6fa4",
          "sha1": "faedd363ffbafde6a23bc7183ce79de11a96e780",
          "md5": "eb3dec19457369611a201727fa984afd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.18"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.1.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-3.2.2.jar",
          "url": "spring-boot-starter-validation-3.2.2.jar",
          "size": 4767,
          "sha512": "7700824d66abba3642d76f377d5a5b199dd27802ffb2c88ae896019e6238551585690aa1eba8f2d6eb3fa00dccc419c0a052abb05948163eed3dc5f06e77019a",
          "sha256": "4ad5b72664bd6ae25ce000ef4f394fa59af33bc9a87eadd538596adae1ae6fa4",
          "sha1": "faedd363ffbafde6a23bc7183ce79de11a96e780",
          "md5": "eb3dec19457369611a201727fa984afd"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-3.2.2.jar",
          "url": "spring-boot-starter-validation-3.2.2.jar",
          "size": 4767,
          "sha512": "7700824d66abba3642d76f377d5a5b199dd27802ffb2c88ae896019e6238551585690aa1eba8f2d6eb3fa00dccc419c0a052abb05948163eed3dc5f06e77019a",
          "sha256": "4ad5b72664bd6ae25ce000ef4f394fa59af33bc9a87eadd538596adae1ae6fa4",
          "sha1": "faedd363ffbafde6a23bc7183ce79de11a96e780",
          "md5": "eb3dec19457369611a201727fa984afd"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-validation-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-3.2.2.jar",
          "url": "spring-boot-starter-validation-3.2.2.jar",
          "size": 4767,
          "sha512": "7700824d66abba3642d76f377d5a5b199dd27802ffb2c88ae896019e6238551585690aa1eba8f2d6eb3fa00dccc419c0a052abb05948163eed3dc5f06e77019a",
          "sha256": "4ad5b72664bd6ae25ce000ef4f394fa59af33bc9a87eadd538596adae1ae6fa4",
          "sha1": "faedd363ffbafde6a23bc7183ce79de11a96e780",
          "md5": "eb3dec19457369611a201727fa984afd"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-validation-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-3.2.2-javadoc.jar",
          "url": "spring-boot-starter-validation-3.2.2-javadoc.jar",
          "size": 4745,
          "sha512": "481292ed6e33a0047908ce7432de76bbbaa80902f4ebb6f3f2c1f01774bd72011094e086a0f053fca31d4af61a7ec518b86e5b701ea583cbb0c25f75d118faf8",
          "sha256": "4a13f819624fc26ed723114bc67ad4d2c4c4fa1d801074cfa84ccdc7cdcae8fb",
          "sha1": "170f9ca642c4985f5a0be8c43b27dd34176d1558",
          "md5": "007e9d9d7e70c90ee8ea105b4b017d0b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-3.2.2-sources.jar",
          "url": "spring-boot-starter-validation-3.2.2-sources.jar",
          "size": 4744,
          "sha512": "8227acfaaa2cd57d887d92a49550e37233f88d43a0cad43974ee1e40e4e7c1ed0ecc8f4f875b86bb2e4839eef8c6cda7518fe7dee4cd92d4f7dcb59e760d2e81",
          "sha256": "e28444cffb3b1e5f7d44f3b65d0c85742070959c8272f89cfd7cd23e2b58feaa",
          "sha1": "bf4d304a82631631abab0c4da2842f717998b7d1",
          "md5": "ace632c4cd5fdda9d57148feee00fa44"
        }
      ]
    }
  ]
}
