{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-web",
    "version": "6.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-web-6.1.3.jar",
          "url": "spring-web-6.1.3.jar",
          "size": 1872520,
          "sha512": "edaf59e78d0bde846c8843efb61c0300d5c30a535321324b39786346f84236fd494bbfff4211dd45e1113579653d156c269297bea047ec8ae901cf4e1b871701",
          "sha256": "7c79d4815954d279a744e04892abb9e13ab730dc25db5813f0b1aef2c04bc818",
          "sha1": "cc3459b4abd436331608ddb6424886875f7086ab",
          "md5": "db6ad06e3a6786e1c67afaf7d9b1b8a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-web-6.1.3.jar",
          "url": "spring-web-6.1.3.jar",
          "size": 1872520,
          "sha512": "edaf59e78d0bde846c8843efb61c0300d5c30a535321324b39786346f84236fd494bbfff4211dd45e1113579653d156c269297bea047ec8ae901cf4e1b871701",
          "sha256": "7c79d4815954d279a744e04892abb9e13ab730dc25db5813f0b1aef2c04bc818",
          "sha1": "cc3459b4abd436331608ddb6424886875f7086ab",
          "md5": "db6ad06e3a6786e1c67afaf7d9b1b8a7"
        }
      ]
    }
  ]
}
