{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-jdbc",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.2.2.jar",
          "url": "spring-boot-starter-jdbc-3.2.2.jar",
          "size": 4769,
          "sha512": "2ae873c480d2ca0d70b1f5109dcd127d150f620ec6b86953779f93c5f709998c5b389a29d36d9fb151ffc2e4edf4dc8076c77bbaad2c75eb509d33b6487c1d73",
          "sha256": "bc917c31af41473f1b8a257d7ff38d69aa2ac31dca09854ff8e6f8249fff164e",
          "sha1": "22ffda6938dca5f584c8b1b64e4e9096e8302c1e",
          "md5": "00663df170cf2359535751741472609d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.2.2.jar",
          "url": "spring-boot-starter-jdbc-3.2.2.jar",
          "size": 4769,
          "sha512": "2ae873c480d2ca0d70b1f5109dcd127d150f620ec6b86953779f93c5f709998c5b389a29d36d9fb151ffc2e4edf4dc8076c77bbaad2c75eb509d33b6487c1d73",
          "sha256": "bc917c31af41473f1b8a257d7ff38d69aa2ac31dca09854ff8e6f8249fff164e",
          "sha1": "22ffda6938dca5f584c8b1b64e4e9096e8302c1e",
          "md5": "00663df170cf2359535751741472609d"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.2.2.jar",
          "url": "spring-boot-starter-jdbc-3.2.2.jar",
          "size": 4769,
          "sha512": "2ae873c480d2ca0d70b1f5109dcd127d150f620ec6b86953779f93c5f709998c5b389a29d36d9fb151ffc2e4edf4dc8076c77bbaad2c75eb509d33b6487c1d73",
          "sha256": "bc917c31af41473f1b8a257d7ff38d69aa2ac31dca09854ff8e6f8249fff164e",
          "sha1": "22ffda6938dca5f584c8b1b64e4e9096e8302c1e",
          "md5": "00663df170cf2359535751741472609d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-jdbc-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.2.2.jar",
          "url": "spring-boot-starter-jdbc-3.2.2.jar",
          "size": 4769,
          "sha512": "2ae873c480d2ca0d70b1f5109dcd127d150f620ec6b86953779f93c5f709998c5b389a29d36d9fb151ffc2e4edf4dc8076c77bbaad2c75eb509d33b6487c1d73",
          "sha256": "bc917c31af41473f1b8a257d7ff38d69aa2ac31dca09854ff8e6f8249fff164e",
          "sha1": "22ffda6938dca5f584c8b1b64e4e9096e8302c1e",
          "md5": "00663df170cf2359535751741472609d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-jdbc-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.2.2-javadoc.jar",
          "url": "spring-boot-starter-jdbc-3.2.2-javadoc.jar",
          "size": 4742,
          "sha512": "64dee54325de9837506fe8bfef218f309cd25b57e3a0cab3396a40b898259d178580f90c78860b29a489cb47015a5edc50c798a49e424dd8b20f7c192cff5b8f",
          "sha256": "ad31c81882185efd3b75efe12505328fb72fc01199c3aa90c8776016b7c34544",
          "sha1": "c93cbbe68832bf4912b126eaad785859a1a71178",
          "md5": "c2e212cf7bc9b94683b1970aa1fbbc72"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.2.2-sources.jar",
          "url": "spring-boot-starter-jdbc-3.2.2-sources.jar",
          "size": 4741,
          "sha512": "482c6b9e6744b4b644b32e9ed4eeca9082ce3681d52bdcf83172f0698c131699c600f8dc0ef7f9cf974cc1526eed6deddc256ce0e0f404486c590bca0164d7f7",
          "sha256": "5ac5a8d8703ecae0fea7c7c9dcda972cf5816997ac028fa30898c27bcee6bdb2",
          "sha1": "571354e44a7ee58e3ad697c29a8a8370287afb91",
          "md5": "70ced29e5203c369d3b6763467777ee1"
        }
      ]
    }
  ]
}
