{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-aop",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.2.jar",
          "url": "spring-boot-starter-aop-3.2.2.jar",
          "size": 4769,
          "sha512": "337c6a7814f25c74e828a1ba2e386975a29e6184753e7256168fa97e07363f910b647e6e07f9c91c9245063815456152a8c8fb6721b8de862719ba010a486a96",
          "sha256": "6606b39d53c018ad9b51f8713cfcb95a13a137961c88f046be8e0ce95d835de2",
          "sha1": "f01ecef0ce5f8d5631890a0c456a88a72323b569",
          "md5": "7465b06dae45797cb6902c4a7a03ab82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.2.jar",
          "url": "spring-boot-starter-aop-3.2.2.jar",
          "size": 4769,
          "sha512": "337c6a7814f25c74e828a1ba2e386975a29e6184753e7256168fa97e07363f910b647e6e07f9c91c9245063815456152a8c8fb6721b8de862719ba010a486a96",
          "sha256": "6606b39d53c018ad9b51f8713cfcb95a13a137961c88f046be8e0ce95d835de2",
          "sha1": "f01ecef0ce5f8d5631890a0c456a88a72323b569",
          "md5": "7465b06dae45797cb6902c4a7a03ab82"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.2.jar",
          "url": "spring-boot-starter-aop-3.2.2.jar",
          "size": 4769,
          "sha512": "337c6a7814f25c74e828a1ba2e386975a29e6184753e7256168fa97e07363f910b647e6e07f9c91c9245063815456152a8c8fb6721b8de862719ba010a486a96",
          "sha256": "6606b39d53c018ad9b51f8713cfcb95a13a137961c88f046be8e0ce95d835de2",
          "sha1": "f01ecef0ce5f8d5631890a0c456a88a72323b569",
          "md5": "7465b06dae45797cb6902c4a7a03ab82"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-aop-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.2.jar",
          "url": "spring-boot-starter-aop-3.2.2.jar",
          "size": 4769,
          "sha512": "337c6a7814f25c74e828a1ba2e386975a29e6184753e7256168fa97e07363f910b647e6e07f9c91c9245063815456152a8c8fb6721b8de862719ba010a486a96",
          "sha256": "6606b39d53c018ad9b51f8713cfcb95a13a137961c88f046be8e0ce95d835de2",
          "sha1": "f01ecef0ce5f8d5631890a0c456a88a72323b569",
          "md5": "7465b06dae45797cb6902c4a7a03ab82"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-aop-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.2-javadoc.jar",
          "url": "spring-boot-starter-aop-3.2.2-javadoc.jar",
          "size": 4741,
          "sha512": "abf7e988fc1d8ec56190a5a7bc8402bff16f6ae8d48dcfa389dbc216b86270b299a4bd37005e5134270166456e0f221737de94a131447ee4c46422850f2af6d8",
          "sha256": "f5791a267215a59a49b0a2878956199d73ae2140f19198910bc8b46d00910113",
          "sha1": "998d233c10c6e497230c39620b53b7bd79bd15b8",
          "md5": "5e09ba127090e224cc91db47fdfa365d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-3.2.2-sources.jar",
          "url": "spring-boot-starter-aop-3.2.2-sources.jar",
          "size": 4740,
          "sha512": "a58c11c1846fe861954045c31a7ddd1cd226b4f77d924e97bb52f831ca34113351bd0c6aa4fa89fe8548f8b5f6dc41b96821524aea1afa0411eaf7cec2299b6c",
          "sha256": "0fb5dddff50612b355fc99ff38f15d3e0f4551c3d82b4ba803fd4325a69408c8",
          "sha1": "a01ad2674fb02ef798702faf78bbb97a5d3062a4",
          "md5": "a3756ab5a2d355e33802d46f561fff4c"
        }
      ]
    }
  ]
}
