{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-orm",
    "version": "6.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-orm-6.1.3.jar",
          "url": "spring-orm-6.1.3.jar",
          "size": 233426,
          "sha512": "10e44823e9279302e7070b1453a96ffdcdbc4e59657e1cc2fa7fbb06db77f23aad8522b806d1ee8119d148eb19e03bbada692d90bd4c7a033ddda66730576b73",
          "sha256": "54d5b35e78b0f5372d047e3faa9b4daa5b8df59467904a17413f8072dfa0934b",
          "sha1": "098572e26c6d011c9710545085358a4e35e27649",
          "md5": "70f2dd4bb77b61579e61c6bddb809107"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-orm-6.1.3.jar",
          "url": "spring-orm-6.1.3.jar",
          "size": 233426,
          "sha512": "10e44823e9279302e7070b1453a96ffdcdbc4e59657e1cc2fa7fbb06db77f23aad8522b806d1ee8119d148eb19e03bbada692d90bd4c7a033ddda66730576b73",
          "sha256": "54d5b35e78b0f5372d047e3faa9b4daa5b8df59467904a17413f8072dfa0934b",
          "sha1": "098572e26c6d011c9710545085358a4e35e27649",
          "md5": "70f2dd4bb77b61579e61c6bddb809107"
        }
      ]
    }
  ]
}
