{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-core",
    "version": "6.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-crypto",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-core-6.2.1.jar",
          "url": "spring-security-core-6.2.1.jar",
          "size": 512814,
          "sha512": "c079ab7d495c93acccc8a50b40a8fd006209c2c452b0449de6b7bc797b009c3188d330a1ad066b8b9912ffc2ced75c3086e48e95158adf3b2406e666ae9f9f53",
          "sha256": "7c3b0c20e19eaa47da2f1141c852e5de17a731436619e1e4ce0845e0775e4686",
          "sha1": "b4014a04f217f0f48d15bc7d53906b6911ad855f",
          "md5": "15ff5f2662bdc1b8936abfd2ef1ad070"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-crypto",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-core-6.2.1.jar",
          "url": "spring-security-core-6.2.1.jar",
          "size": 512814,
          "sha512": "c079ab7d495c93acccc8a50b40a8fd006209c2c452b0449de6b7bc797b009c3188d330a1ad066b8b9912ffc2ced75c3086e48e95158adf3b2406e666ae9f9f53",
          "sha256": "7c3b0c20e19eaa47da2f1141c852e5de17a731436619e1e4ce0845e0775e4686",
          "sha1": "b4014a04f217f0f48d15bc7d53906b6911ad855f",
          "md5": "15ff5f2662bdc1b8936abfd2ef1ad070"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-core-6.2.1-javadoc.jar",
          "url": "spring-security-core-6.2.1-javadoc.jar",
          "size": 1263884,
          "sha512": "5835775f94fba031250130327bc8050facb679e22301a82feb887d695c58a633a8306a6f0ac9301226b8d4f5ac09794b7921e8c6d11e1e6bca7aa7eed7700cba",
          "sha256": "09d7ea5f719c0207ef4598131eb7ec17212617c7221773996515000181342196",
          "sha1": "39a56ec7546b49d0dc624e7ba9bc5791aa7528e2",
          "md5": "ca4e34cba666c19d315020bee4bd53af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-core-6.2.1-sources.jar",
          "url": "spring-security-core-6.2.1-sources.jar",
          "size": 504678,
          "sha512": "9c8cd641d8b165405794f7ba3c2d03a99925da9d450721339d3a2cd8960797e6ec0e1c9c0853d214d62a004df1cbba6fab2a7bcb94f7d32ade3540ff4c158601",
          "sha256": "58e27de1c8ba82249cd65aa41ddd1b28775841582f7ae31979015e678df8f796",
          "sha1": "cd35c4c4bf672a03499c98bfc61baa0e741c2505",
          "md5": "011a1f991862afae82b8cc488823f2f6"
        }
      ]
    }
  ]
}
