{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.2.2.jar",
          "url": "spring-boot-starter-3.2.2.jar",
          "size": 4768,
          "sha512": "14c049accf3f9fd2408a553c89a9fbc78f9bc32c7cb8a1d9bd39e10ba0b7ac2b48b81dd8ec6e213c3fc57ffb99a65c6efec6c51554ca322b5f53fb3d9a37f559",
          "sha256": "2e7b5a2f475f52f4cd5055a2ae6bae7a9c15e198b43f7e56a4b56df3941a837c",
          "sha1": "dc04714f9295297f92fa8099eb51edc54dbe67db",
          "md5": "83b394eaeea9596494d485951c0aaee3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.2.2.jar",
          "url": "spring-boot-starter-3.2.2.jar",
          "size": 4768,
          "sha512": "14c049accf3f9fd2408a553c89a9fbc78f9bc32c7cb8a1d9bd39e10ba0b7ac2b48b81dd8ec6e213c3fc57ffb99a65c6efec6c51554ca322b5f53fb3d9a37f559",
          "sha256": "2e7b5a2f475f52f4cd5055a2ae6bae7a9c15e198b43f7e56a4b56df3941a837c",
          "sha1": "dc04714f9295297f92fa8099eb51edc54dbe67db",
          "md5": "83b394eaeea9596494d485951c0aaee3"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.2.2.jar",
          "url": "spring-boot-starter-3.2.2.jar",
          "size": 4768,
          "sha512": "14c049accf3f9fd2408a553c89a9fbc78f9bc32c7cb8a1d9bd39e10ba0b7ac2b48b81dd8ec6e213c3fc57ffb99a65c6efec6c51554ca322b5f53fb3d9a37f559",
          "sha256": "2e7b5a2f475f52f4cd5055a2ae6bae7a9c15e198b43f7e56a4b56df3941a837c",
          "sha1": "dc04714f9295297f92fa8099eb51edc54dbe67db",
          "md5": "83b394eaeea9596494d485951c0aaee3"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.2.2.jar",
          "url": "spring-boot-starter-3.2.2.jar",
          "size": 4768,
          "sha512": "14c049accf3f9fd2408a553c89a9fbc78f9bc32c7cb8a1d9bd39e10ba0b7ac2b48b81dd8ec6e213c3fc57ffb99a65c6efec6c51554ca322b5f53fb3d9a37f559",
          "sha256": "2e7b5a2f475f52f4cd5055a2ae6bae7a9c15e198b43f7e56a4b56df3941a837c",
          "sha1": "dc04714f9295297f92fa8099eb51edc54dbe67db",
          "md5": "83b394eaeea9596494d485951c0aaee3"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.2.2-javadoc.jar",
          "url": "spring-boot-starter-3.2.2-javadoc.jar",
          "size": 4734,
          "sha512": "0b13a30d4037a2930e88c23bf2e043ad3dc18aad30934de9803e93e30bd704ae3108cbe08f159fb33a5381d959b1b588d8050461ac7582ead732be89c47017e9",
          "sha256": "491471f27fc47f28e7f1f4d276e9d7b5d650b2d2d7ca483070a9eb1b1674c494",
          "sha1": "b01c6abceacac0e4e0627825572d1cb5f5ac2183",
          "md5": "7dcfe27833d1609074faed78e6035a02"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.2.2-sources.jar",
          "url": "spring-boot-starter-3.2.2-sources.jar",
          "size": 4733,
          "sha512": "e29e0454da9e0a61ecde2aef1737a140a527e70971f58acf88a3e142650e19c39e8614829b4c96dbb1115618bc7c0a1f5a73e6766f684902445d3cea7c613d6a",
          "sha256": "dfa4ad76ef805caae41e24c85722cc0cc07abded122120f5e5b32c48c39e1bcb",
          "sha1": "8147d7dde8e94cef2f77e6c129fd6c4684a6738f",
          "md5": "1baf658e501632cffce1a27be4360f13"
        }
      ]
    }
  ]
}
