{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-jdbc",
    "version": "6.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-jdbc-6.1.3.jar",
          "url": "spring-jdbc-6.1.3.jar",
          "size": 460578,
          "sha512": "9413463c88504551c4eb81ebc7fde067be745d00f1c9423fd54e42bd728123c373d521d3a9b76a99cae9227872f61a781cb0f6afbc6b93ccfd8798480d65d6c5",
          "sha256": "a917fd909613c09ba42327d36df66e51937b23dafaa373fc32e70160594e5986",
          "sha1": "be4b30cc956b26f13e04ccadc2b0575038c531bb",
          "md5": "2584132ea913659eeb671947c4786f8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-jdbc-6.1.3.jar",
          "url": "spring-jdbc-6.1.3.jar",
          "size": 460578,
          "sha512": "9413463c88504551c4eb81ebc7fde067be745d00f1c9423fd54e42bd728123c373d521d3a9b76a99cae9227872f61a781cb0f6afbc6b93ccfd8798480d65d6c5",
          "sha256": "a917fd909613c09ba42327d36df66e51937b23dafaa373fc32e70160594e5986",
          "sha1": "be4b30cc956b26f13e04ccadc2b0575038c531bb",
          "md5": "2584132ea913659eeb671947c4786f8e"
        }
      ]
    }
  ]
}
