{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-config",
    "version": "6.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-config-6.2.1.jar",
          "url": "spring-security-config-6.2.1.jar",
          "size": 1808353,
          "sha512": "3605f35b7df969fbb67662b5f692e68a4a7d8dcb6969ab2d98a7c2d4c258122d2623d0bc601bf3024269b16bd67e1e3b8f7eebc76f4f4a60fe489fed548cf904",
          "sha256": "361ec68075e9c8c508a7e81036de319a27ace3c2eba96dddcf85177744e6a282",
          "sha1": "119953fd2980d50e1119b913a8596e5e6bdc1295",
          "md5": "4d65ce9406de0a9c1a3d421e66e9855c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-config-6.2.1.jar",
          "url": "spring-security-config-6.2.1.jar",
          "size": 1808353,
          "sha512": "3605f35b7df969fbb67662b5f692e68a4a7d8dcb6969ab2d98a7c2d4c258122d2623d0bc601bf3024269b16bd67e1e3b8f7eebc76f4f4a60fe489fed548cf904",
          "sha256": "361ec68075e9c8c508a7e81036de319a27ace3c2eba96dddcf85177744e6a282",
          "sha1": "119953fd2980d50e1119b913a8596e5e6bdc1295",
          "md5": "4d65ce9406de0a9c1a3d421e66e9855c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-config-6.2.1-javadoc.jar",
          "url": "spring-security-config-6.2.1-javadoc.jar",
          "size": 1111550,
          "sha512": "ff0cd72d252cfc5c047ee6cfa46aefb76e8eb6e5d235c80ad050ad20d47292266e104668c08b927f6645d0544998f349c85874f0e00b69e60a3468f6081c2d10",
          "sha256": "f6770bd24dced72fcaa2130f768536193c27e560a3e0810135a9b27774395bff",
          "sha1": "4ef54f25e73ba589ae37fbcba4afbe7baae4a899",
          "md5": "ff1e86e064f450993c8d0cdc9d2a5b54"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-config-6.2.1-sources.jar",
          "url": "spring-security-config-6.2.1-sources.jar",
          "size": 1246826,
          "sha512": "921393676480456931ea9c69be26041ed6bdd73f88a80ce5721938a2563ac6ea4a54b61de1175a8484961c44ae4eab6a3b81d2060196d4e4557d17729476ebb0",
          "sha256": "79954d60bd6ade0ece78308335a7b15e025ab3bfee990f728eb25a248916b8f3",
          "sha1": "0d2746b2976fbc9f3e8d1ab11b5002aab952f59e",
          "md5": "d1b4865b58ce2f9da33e8dc931cb79b2"
        },
        {
          "name": "spring-security-config-6.2.1-sources.jar",
          "url": "spring-security-config-6.2.1-sources.jar",
          "size": 1246826,
          "sha512": "921393676480456931ea9c69be26041ed6bdd73f88a80ce5721938a2563ac6ea4a54b61de1175a8484961c44ae4eab6a3b81d2060196d4e4557d17729476ebb0",
          "sha256": "79954d60bd6ade0ece78308335a7b15e025ab3bfee990f728eb25a248916b8f3",
          "sha1": "0d2746b2976fbc9f3e8d1ab11b5002aab952f59e",
          "md5": "d1b4865b58ce2f9da33e8dc931cb79b2"
        }
      ]
    }
  ]
}
